steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/pca-demo-repo/pca-flask-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/pca-demo-repo/pca-flask-app']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'pca-flask-app',
        '--image',
        'us-central1-docker.pkg.dev/$PROJECT_ID/pca-demo-repo/pca-flask-app',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--service-account',
        'cloud-build-deployer@$PROJECT_ID.iam.gserviceaccount.com'
      ]

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/pca-demo-repo/pca-flask-app'
