apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: pca-flask-pipeline
description: CI/CD pipeline for PCA Flask App
serialPipeline:
  stages:
    - targetId: staging
      profiles: [staging]
    - targetId: production
      profiles: [production]
